# Background and foreground colors
background = #0d0e10
foreground = #E1E1E1

# Standard colors
palette = 0=#0d0e10
palette = 1=#b46958
palette = 2=#8DAA9A
palette = 3=#F4BF75
palette = 4=#80909F
palette = 5=#AA749F
palette = 6=#88AFA2
palette = 7=#E1E1E1

# Bright colors
palette = 8=#202020
palette = 9=#c87e6b
palette = 10=#a8c070
palette = 11=#f9dfb2
palette = 12=#A2B5C1
palette = 13=#bf8ab4
palette = 14=#a2c2b7
palette = 15=#FFFFFF
