background            #0d0e10
foreground            #E1E1E1

# black
color0  #0d0e10
color8  #202020

# red
color1  #b46958
color9  #c87e6b

# green
color2  #8DAA9A
color10 #a8c070

# yellow
color3  #F4BF75
color11 #f9dfb2

# blue
color4  #80909F
color12 #A2B5C1

# magenta
color5  #AA749F
color13 #bf8ab4

#cyan
color6  #88AFA2
color14 #a2c2b7

#white
color7  #E1E1E1
color15 #FFFFFF


